sudo: False

language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test python=$TRAVIS_PYTHON_VERSION -c defaults -c conda-forge thrift python-snappy numpy pandas numba cython setuptools bson lz4 zstandard pytest
  - source activate test

script:
  - python setup.py install
  - python setup.py test

notifications:
  email: false
